---

- name: 'update umask in login.conf'
  lineinfile:
    dest: '/etc/login.conf'
    regexp: "^(\\s+):umask=.*:"
    line: "\\1:umask={{ umask_mode }}:\\\\"
    owner: 'root'
    group: 'wheel'
    mode: '0644'
    backrefs: True
