---

- hosts: all
  name: 'Verify'
  become: True
  gather_facts: True
  vars:
    __verify_touch1_by_os_family:
      Debian: "su -c 'touch /tmp/fic1 && mkdir /tmp/dir1' molecule"
      OpenBSD: "su -l molecule -c 'touch /tmp/fic1 && mkdir /tmp/dir1'"

    __verify_login_by_os_family:
      Debian: '/etc/login.defs'
      OpenBSD: '/etc/login.conf'

    __verify_login_check_by_os_family:
      Debian: '^UMASK\s+027'
      OpenBSD: ':umask=027:'

  tasks:
    - name: 'Cleaning'
      file:
        path: "{{ item.path }}"
        state: 'absent'
      loop:
        - path: '/tmp/fic1'
        - path: '/tmp/dir1'

    - name: 'Create a file and a directory'
      shell: "{{ __verify_touch1_by_os_family[ ansible_facts['os_family'] ] }}"

    - name: 'Check file stat'
      stat:
        path: '/tmp/fic1'
      register: __verify_file_stat

    - name: 'Check directory stat'
      stat:
        path: '/tmp/dir1'
      register: __verify_dir_stat

    - name: 'Check file and directory'
      assert:
        that:
          - __verify_file_stat.stat.exists
          - __verify_file_stat.stat.isreg
          - __verify_file_stat.stat.mode == '0640'
          - __verify_dir_stat.stat.exists
          - __verify_dir_stat.stat.isdir
          - __verify_dir_stat.stat.mode == '0750'

    - name: 'Check login definitions file'
      slurp:
        path: "{{ __verify_login_by_os_family[ ansible_facts['os_family'] ] }}"
      register: __verify_config
      failed_when: not __verify_config['content'] | b64decode | regex_search(__verify_login_check_by_os_family[ ansible_facts['os_family'] ], multiline=True)
